---
title: "Preliminary Graphs"
author: "Kayla Manning"
date: "2/24/2020"
output: html_document
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = FALSE)
library(tidyverse)
library(gt)
library(gridExtra)
library(lubridate)

tidy_int_reg_bag <- read_csv("raw-data/all_tidy.csv",
                             col_types = cols(col_date(format = ''),
                                             col_character(),
                                             col_character(),
                                             col_character(),
                                             col_character(),
                                             col_character(),
                                             col_double()))

```


```{r house_year_type_bar, warning = FALSE}

# need to create this named list so I can change the facet labels on plot

int_reg <- c("Interhouse", "Regular")
names(int_reg) <- c("int", "reg")

# generating plot that displays interhouse and regular side-by-side

tidy_int_reg_bag %>% 
  filter(type %in% c("reg", "int"),
         house != "Annenberg",
         house != "FlyBy",
         house != "Hillel",
         meal == "Lunch") %>% 
  group_by(house, type, year) %>% 
  summarize(avg = median(count, na.rm = TRUE)) %>% 
  ggplot(aes(house, avg, fill = year)) +
    geom_col(position = position_dodge(-0.9)) +
    facet_wrap(~ type, labeller = labeller(type = int_reg)) +
    coord_flip() +
    ylab("Median Swipe Count") +
    xlab("House") +
    labs(title = "House Median Lunch Swipe Counts") +
    scale_fill_discrete(name = "Academic Year",
                        labels = c("2017-2018", "2018-2019"))

ggsave("final_project_shiny/int-reg-lunch-houses/house_lunch_both.png")

# now just interhouse

tidy_int_reg_bag %>% 
  filter(type == "int",
         house != "Annenberg",
         house != "FlyBy",
         house != "Hillel",
         meal == "Lunch") %>% 
  group_by(house, type, year) %>% 
  summarize(avg = median(count, na.rm = TRUE)) %>% 
  ggplot(aes(house, avg, fill = year)) +
    geom_col(position = position_dodge(-0.9)) +
    facet_wrap(~ type, labeller = labeller(type = int_reg)) +
    coord_flip() +
    ylab("Median Swipe Count") +
    xlab("House") +
    labs(title = "House Median Lunch Swipe Counts, Interhouse Only") +
    scale_fill_discrete(name = "Academic Year",
                        labels = c("2017-2018", "2018-2019"))

ggsave("final_project_shiny/int-reg-lunch-houses/house_lunch_int.png")

# now just regular

tidy_int_reg_bag %>% 
  filter(type == "reg",
         house != "Annenberg",
         house != "FlyBy",
         house != "Hillel",
         meal == "Lunch") %>% 
  group_by(house, type, year) %>% 
  summarize(avg = median(count, na.rm = TRUE)) %>% 
  ggplot(aes(house, avg, fill = year)) +
    geom_col(position = position_dodge(-0.9)) +
    facet_wrap(~ type, labeller = labeller(type = int_reg)) +
    coord_flip() +
    ylab("Median Swipe Count") +
    xlab("House") +
    labs(title = "House Median Lunch Swipe Counts, Residents Only") +
    scale_fill_discrete(name = "Academic Year",
                        labels = c("2017-2018", "2018-2019"))

ggsave("final_project_shiny/int-reg-lunch-houses/house_lunch_reg.png")

interhouse_flyby_increase <- tidy_int_reg_bag %>% 
  filter(house == "FlyBy",
         meal == "Lunch",
         type == "int") %>% 
  group_by(year) %>% 
  summarise(median = median(count)) %>% 
  select(median) %>% 
  summarise(diff = median[2] - median[1])


```

FlyBy appears to have the greatest increase (everyone is considered interhouse). The difference in median swipe counts from the 2017-2018 to the 2018-2019 academic year is `r interhouse_flyby_increase`.

```{r pct_swipe_increase_by_meal}

# want to find the increase in percent of interhouse swipes for each meal week
# breakfast first
# change column title and add a footnote

tidy_int_reg_bag %>%
  select(house, type, meal, year, count) %>% 
  filter(type %in% c("int", "grand_total"),
         house != "FlyBy",
         house != "Hillel",
         meal != "Day Total",
         meal == "Breakfast") %>% 
  group_by(house, year, type) %>% 
  summarize(count_type = median(count, na.rm = TRUE)) %>% 
  pivot_wider(names_from = type, values_from = count_type) %>% 
  mutate(percent_int = int / grand_total * 100) %>% 
  select(house, year, percent_int) %>% 
  pivot_wider(names_from = year, values_from = percent_int) %>% 
  mutate(difference = `1819` - `1718`) %>% 
  arrange(desc(difference)) %>%
  select(house, difference) %>% 
  ggplot(aes(house, difference, fill = house)) +
  geom_col() +
  coord_flip() +
  labs(title = "Change in Interhouse at Breakfast",
       subtitle = "Calculated as the difference in the percent of median \ninterhouse swipes in 2017-2018 and 2018-2019") +
  xlab("Difference") +
  ylab("House") +
  theme(legend.position = "none")

# saving image for shiny

ggsave("final_project_shiny/change-interhouse-meal/change_int_bfast.png")

# commenting this out but I could get rid of the ggplot and add this to get a
# nice gt table

  # gt(rowname_col = "house", 
  #    groupname_col = FALSE) %>% 
  # cols_label("difference" = "Percent Change in Interhouse Swipes") %>% 
  # tab_header("Change in Interhouse at Breakfast")  %>% 
  # tab_footnote("Calculated as the difference in the percent of median interhouse swipes in 2017-2018 and 2018-2019", locations = cells_column_labels(columns = vars(difference)))

# now lunch

tidy_int_reg_bag %>%
  select(house, type, meal, year, count) %>% 
  filter(type %in% c("int", "grand_total"),
         house != "FlyBy",
         house != "Hillel",
         meal != "Day Total",
         meal == "Lunch") %>% 
  group_by(house, year, type) %>% 
  summarize(count_type = median(count, na.rm = TRUE)) %>% 
  pivot_wider(names_from = type, values_from = count_type) %>% 
  mutate(percent_int = int / grand_total * 100) %>% 
  select(house, year, percent_int) %>% 
  pivot_wider(names_from = year, values_from = percent_int) %>% 
  mutate(difference = `1819` - `1718`) %>% 
  arrange(desc(difference)) %>%
  select(house, difference) %>% 
  ggplot(aes(house, difference, fill = house)) +
  geom_col() +
  coord_flip() +
  labs(title = "Change in Interhouse at Lunch",
       subtitle = "Calculated as the difference in the percent of median \ninterhouse swipes in 2017-2018 and 2018-2019") +
  xlab("Difference") +
  ylab("House") +
  theme(legend.position = "none")

# saving for access in shiny app

ggsave("final_project_shiny/change-interhouse-meal/change_int_lunch.png")  

  # gt(rowname_col = "house", 
  #    groupname_col = FALSE) %>% 
  # cols_label("difference" = "Percent Change in Interhouse Swipes") %>% 
  # tab_header("Change in Interhouse at Lunch") %>% 
  # tab_footnote("Calculated as the difference in the percent of median interhouse swipes in 2018-2018 and 2018-2019", locations = cells_column_labels(columns = vars(difference)))

# dinner

tidy_int_reg_bag %>%
  select(house, type, meal, year, count) %>% 
  filter(type %in% c("int", "grand_total"),
         house != "FlyBy",
         house != "Hillel",
         meal != "Day Total",
         meal == "Dinner") %>% 
  group_by(house, year, type) %>% 
  summarize(count_type = median(count, na.rm = TRUE)) %>% 
  pivot_wider(names_from = type, values_from = count_type) %>% 
  mutate(percent_int = int / grand_total * 100) %>% 
  select(house, year, percent_int) %>% 
  pivot_wider(names_from = year, values_from = percent_int) %>% 
  mutate(difference = `1819` - `1718`) %>% 
  arrange(desc(difference)) %>%
  select(house, difference) %>% 
  ggplot(aes(house, difference, fill = house)) +
  geom_col() +
  coord_flip() +
  labs(title = "Change in Interhouse at Dinner",
       subtitle = "Calculated as the difference in the percent of median \ninterhouse swipes in 2017-2018 and 2018-2019") +
  xlab("Difference") +
  ylab("House") +
  theme(legend.position = "none")
  
# saving for shiny

ggsave("final_project_shiny/change-interhouse-meal/change_int_dinner.png")

  #   gt(rowname_col = "house", 
  #    groupname_col = FALSE) %>% 
  # cols_label("difference" = "Percent Change in Interhouse Swipes") %>% 
  # tab_header("Change in Interhouse at Dinner")  %>% 
  # tab_footnote("Calculated as the difference in the percent of median interhouse swipes in 2018-2018 and 2018-2019", locations = cells_column_labels(columns = vars(difference)))




```

```{r raw_change_interhouse}

# want to find the increase in median interhouse swipes for each meal week
# breakfast first

tidy_int_reg_bag %>%
  select(house, type, meal, year, count) %>% 
  filter(type == "int",
         house != "FlyBy",
         house != "Hillel",
         meal != "Day Total",
         meal == "Breakfast") %>% 
  group_by(house, year, type) %>% 
  summarize(count_type = median(count, na.rm = TRUE)) %>% 
  pivot_wider(names_from = year, values_from = count_type) %>% 
  mutate(difference = `1819` - `1718`) %>% 
  select(house, difference) %>% 
  ggplot(aes(house, difference, fill = house)) +
  geom_col() +
  coord_flip() +
  labs(title = "Change in Interhouse at Breakfast",
       subtitle = "Calculated as the difference in median \ninterhouse swipes in 2017-2018 and 2018-2019") +
  xlab("Difference") +
  ylab("House") +
  theme(legend.position = "none")

# saving image for shiny

ggsave("final_project_shiny/raw-change-interhouse-meal/raw_change_int_bfast.png")

# lunch

# want to find the increase in median interhouse swipes for each meal week
# breakfast first

tidy_int_reg_bag %>%
  select(house, type, meal, year, count) %>% 
  filter(type == "int",
         house != "FlyBy",
         house != "Hillel",
         meal != "Day Total",
         meal == "Lunch") %>% 
  group_by(house, year, type) %>% 
  summarize(count_type = median(count, na.rm = TRUE)) %>% 
  pivot_wider(names_from = year, values_from = count_type) %>% 
  mutate(difference = `1819` - `1718`) %>% 
  select(house, difference) %>% 
  ggplot(aes(house, difference, fill = house)) +
  geom_col() +
  coord_flip() +
  labs(title = "Change in Interhouse at Lunch",
       subtitle = "Calculated as the difference in median \ninterhouse swipes in 2017-2018 and 2018-2019") +
  xlab("Difference") +
  ylab("House") +
  theme(legend.position = "none")

# saving image for shiny

ggsave("final_project_shiny/raw-change-interhouse-meal/raw_change_int_lunch.png")

# now dinner!

# want to find the increase in median interhouse swipes for each meal week
# breakfast first

tidy_int_reg_bag %>%
  select(house, type, meal, year, count) %>% 
  filter(type == "int",
         house != "FlyBy",
         house != "Hillel",
         meal != "Day Total",
         meal == "Dinner") %>% 
  group_by(house, year, type) %>% 
  summarize(count_type = median(count, na.rm = TRUE)) %>% 
  pivot_wider(names_from = year, values_from = count_type) %>% 
  mutate(difference = `1819` - `1718`) %>% 
  select(house, difference) %>% 
  ggplot(aes(house, difference, fill = house)) +
  geom_col() +
  coord_flip() +
  labs(title = "Change in Interhouse at Dinner",
       subtitle = "Calculated as the difference in median \ninterhouse swipes in 2017-2018 and 2018-2019") +
  xlab("Difference") +
  ylab("House") +
  theme(legend.position = "none")

# saving image for shiny

ggsave("final_project_shiny/raw-change-interhouse-meal/raw_change_int_dinner.png")

```


```{r}

tidy_int_reg_bag$meal <-  fct_relevel(tidy_int_reg_bag$meal, "Breakfast", "Lunch", "Dinner")
tidy_int_reg_bag <- with(tidy_int_reg_bag, 
                         tidy_int_reg_bag[order(year, -as.numeric(year)), ])

tidy_int_reg_bag$meal <- fct_relevel(tidy_int_reg_bag$meal, 
                                     c("Breakfast", "Lunch", "Dinner"))

# swipe counts for each year by house, faceted by meal

tidy_int_reg_bag %>%
  select(house, type, meal, year, count) %>% 
  filter(type %in% c("int", "grand_total"),
         house != "FlyBy",
         house != "Hillel",
         house != "Annenberg",
         meal != "Day Total",
         meal != "Brain Break") %>% 
  group_by(house, year, meal, type) %>% 
  summarize(avg = median(count, na.rm = TRUE)) %>% 
  ggplot(aes(house, avg, fill = year)) +
    geom_col(position = position_dodge(-0.9)) +
    facet_wrap(~ meal) +
    coord_flip() +
    labs(title = "Swipe Counts by House and Meal") +
    scale_fill_discrete(name = "Academic Year",
                        labels = c("2017-2018", "2018-2019")) +
    xlab("Location") +
    ylab("Median Swipe Counts")


# swipe counts for each year by meal, faceted by house

tidy_int_reg_bag %>%
  select(house, type, meal, year, count) %>% 
  filter(type %in% c("int", "grand_total"),
         house != "FlyBy",
         house != "Hillel",
         house != "Annenberg") %>% 
  group_by(house, year, meal, type) %>% 
  summarize(avg = median(count, na.rm = TRUE)) %>% 
  ggplot(aes(meal, avg, fill = year)) +
    geom_col(position = position_dodge(-0.9)) +
    facet_wrap(~ house) +
    coord_flip() +
    labs(title = "Swipe Counts by House and Meal") +
    scale_fill_discrete(name = "Academic Year",
                        labels = c("2017-2018", "2018-2019")) +
    scale_x_discrete(limits = rev(levels(tidy_int_reg_bag$meal))) +
    xlab("Location") +
    ylab("Median Swipe Counts")

```



```{r flyby_increase}

tidy_int_reg_bag$day <- recode(tidy_int_reg_bag$day,
                               "Mon" = "Monday",
                               "Tue" = "Tuesday",
                               "Wed" = "Wednesday",
                               "Thu" = "Thursday",
                               "Fri" = "Friday") %>% 
  fct_relevel(c("Monday", "Tuesday", "Wednesday", "Thursday", "Friday"))


tidy_int_reg_bag %>% 
  filter(house == "FlyBy",
         meal == "Lunch") %>% 
  group_by(day, year) %>% 
  summarise(average = median(count, na.rm = TRUE),
            average = round(average, 0)) %>% 
  pivot_wider(names_from = year, values_from = average) %>% 
  mutate(increase = `1819` - `1718`) %>% 
  arrange(desc(increase)) %>% 
  gt(rowname_col = "day", 
     groupname_col = FALSE) %>% 
  tab_header("Average Daily Increase in FlyBy Traffic") %>% 
  cols_label(`1718` = "2017-2018",
             `1819` = "2018-2019",
             increase = "Increase") %>% 
  cols_align("center") %>% 
  tab_footnote("Difference in Median Swipe Counts for 2017-2018 and 2018-2019 Academic Years", locations = cells_title("title"))

# going to plot the increase column as a boxplot

tidy_int_reg_bag %>% 
  filter(house == "FlyBy",
         meal == "Lunch") %>% 
  ggplot(aes(year, count, fill = year)) +
  geom_boxplot() +
  facet_wrap("day") +
  labs(title = "Distribution of Fly-By Traffic") +
  scale_fill_discrete(name = "Academic Year",
                      labels = c("2017-2018", "2018-2019")) +
  xlab("Academic Year") +
  scale_x_discrete(labels = c("2017-2018", "2018-2019")) +
  ylab("Count")

# creating barplots that show each individual column from gt table, and both years
# side-by-side

# side-by-side years first

tidy_int_reg_bag %>% 
  filter(house == "FlyBy",
         meal == "Lunch") %>% 
  group_by(day, year) %>% 
  summarise(average = median(count, na.rm = TRUE),
            average = round(average, 0)) %>% 
  pivot_wider(names_from = year, values_from = average) %>% 
  mutate(increase = `1819` - `1718`) %>% 
  pivot_longer(cols = 2:4, names_to = "variable", values_to = "counts") %>% 
  filter(variable != "increase") %>% 
  ggplot(aes(day, counts, fill = variable)) +
  geom_col(position = "dodge") +
  labs(title = "Daily Distribution of Fly-By Traffic",
       subtitle = "Comparing median swipe counts for the 2017-2018 and 2018-2019 \nacademic years") +
  scale_fill_discrete(name = "Academic Year",
                      labels = c("2017-2018", "2018-2019")) +
  xlab("Day of the Week") +
  ylab("Median Swipe Count")

ggsave("final_project_shiny/flyby-daily-counts/both.png")

# now just 2017-2018

tidy_int_reg_bag %>% 
  filter(house == "FlyBy",
         meal == "Lunch") %>% 
  group_by(day, year) %>% 
  summarise(average = median(count, na.rm = TRUE),
            average = round(average, 0)) %>% 
  pivot_wider(names_from = year, values_from = average) %>% 
  mutate(increase = `1819` - `1718`) %>% 
  pivot_longer(cols = 2:4, names_to = "variable", values_to = "counts") %>% 
  filter(variable == "1718") %>% 
  ggplot(aes(day, counts, fill = variable)) +
  geom_col(position = "dodge") +
  labs(title = "Daily Distribution of Fly-By Traffic in 2017-2018",
       subtitle = "In terms of median swipe counts") +
  theme(legend.position = "none") +
  xlab("Day of the Week") +
  ylab("Median Swipe Count")

ggsave("final_project_shiny/flyby-daily-counts/1718.png")
  
# now just 2018-2019

tidy_int_reg_bag %>% 
  filter(house == "FlyBy",
         meal == "Lunch") %>% 
  group_by(day, year) %>% 
  summarise(average = median(count, na.rm = TRUE),
            average = round(average, 0)) %>% 
  pivot_wider(names_from = year, values_from = average) %>% 
  mutate(increase = `1819` - `1718`) %>% 
  pivot_longer(cols = 2:4, names_to = "variable", values_to = "counts") %>% 
  filter(variable == "1819") %>% 
  ggplot(aes(day, counts, fill = variable)) +
  geom_col(position = "dodge") +
  labs(title = "Daily Distribution of Fly-By Traffic in 2018-2019",
       subtitle = "In terms of median swipe counts") +
  theme(legend.position = "none") +
  xlab("Day of the Week") +
  ylab("Median Swipe Count")

ggsave("final_project_shiny/flyby-daily-counts/1819.png")

# now just increase

tidy_int_reg_bag %>% 
  filter(house == "FlyBy",
         meal == "Lunch") %>% 
  group_by(day, year) %>% 
  summarise(average = median(count, na.rm = TRUE),
            average = round(average, 0)) %>% 
  pivot_wider(names_from = year, values_from = average) %>% 
  mutate(increase = `1819` - `1718`) %>% 
  pivot_longer(cols = 2:4, names_to = "variable", values_to = "counts") %>% 
  filter(variable == "increase") %>% 
  ggplot(aes(day, counts, fill = variable)) +
  geom_col(position = "dodge") +
  labs(title = "Increase in Daily Distribution of Fly-By Traffic",
       subtitle = "The increase in median swipe counts for the 2017-2018 and 2018-2019 \nacademic years") +
  theme(legend.position = "none") +
  xlab("Day of the Week") +
  ylab("Difference in Median Swipe Counts")

ggsave("final_project_shiny/flyby-daily-counts/increase.png")


```

