---
title: "Animation"
author: "Kayla Manning"
date: "4/13/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(tidyverse)
library(gganimate)
library(lubridate)
library(gt)

tidy_int_reg_bag <- read_csv("all_tidy.csv",
                             col_types = cols(col_date(format = ''),
                                             col_character(),
                                             col_character(),
                                             col_character(),
                                             col_character(),
                                             col_character(),
                                             col_double()))
```


```{r}

anim_data <- tidy_int_reg_bag %>% 
  filter(house != "Annenberg",
         house != "Hillel",
         type %in% c("int", "grand_total")) %>% 
  mutate(distance = ifelse(house == "Adams", 1024.32, NA),
         distance = ifelse(house == "Quincy", 1436.10, distance),
         distance = ifelse(house == "Lowell", 1062.31, distance),
         distance = ifelse(house == "Leverett", 1750.81, distance),
         distance = ifelse(house == "Dunster", 2180.38, distance),
         distance = ifelse(house == "Mather", 2264.54, distance),
         distance = ifelse(house == "Winthrop", 1599.63, distance),
         distance = ifelse(house == "Eliot", 1877.21, distance),
         distance = ifelse(house == "Kirkland", 1740.05, distance),
         distance = ifelse(house == "Cabot", 3173.44, distance),
         distance = ifelse(house == "Currier", 3486.88, distance),
         distance = ifelse(house == "Pforzheimer", 3457.24, distance),
         distance = ifelse(house == "FlyBy", 641.54, distance),
         neighborhood = ifelse(house %in% c("Adams", "Quincy", "Lowell"), 
                               "River Central", NA),
         neighborhood = ifelse(house %in% c("Leverett", "Dunster", "Mather"),
                               "River West", neighborhood),
         neighborhood = ifelse(house %in% c("Winthrop", "Eliot", "Kirkland"), 
                               "River East", neighborhood),
         neighborhood = ifelse(house %in% c("Cabot", "Currier", "Pforzheimer"),
                               "Quad", neighborhood),
         neighborhood = ifelse(house == "FlyBy", "Yard", neighborhood)) %>% 
  group_by(house, type, distance, neighborhood, date, year) %>% 
  summarize(avg_count = median(count, na.rm = TRUE)) %>% 
  pivot_wider(names_from = type, values_from = avg_count) %>% 
  
  # I want to create a month column so the animation isn't jumping around as
  # much (as it is right now with the daily values); I will find the average
  # counts by month. In order to do this, I will have to group by month and year
  # before doing the summarize command.
  
  arrange(date) %>% 
  mutate(month_year = paste(month(date), year(date), sep = "/")) %>% 
  group_by(month_year, distance, house, neighborhood, year) %>% 
  summarize(avg_int = median(int, na.rm = TRUE),
            avg_total = median(grand_total, na.rm = TRUE))

anim_data$month_year <- fct_relevel(anim_data$month_year, "8/2017", 
                                        "9/2017", "10/2017", "11/2017",
                                        "12/2017", "1/2018", "2/2018", "3/2018",
                                        "4/2018", "9/2018", "10/2018", "11/2018",
                                        "12/2018", "1/2019", "2/2019", "3/2019",
                                        "4/2019", "5/2019")

# saving this data as a csv file so I can easily call for it in my shiny app

write_csv(anim_data, "anim_data.csv")

p <- anim_data %>% 
  mutate(House = house) %>% 
  ggplot(aes(distance, avg_int, color = House)) +
  geom_point() +
  geom_label(aes(label = House), 
             label.padding = unit(0.1, "lines")) +
  labs(title = "Relationship between Time, Distance, and House \non Interhouse Swipe Counts",
       subtitle = "Date: {current_frame}") +
  transition_manual(month_year) +
  scale_y_continuous(limits = c(0, 600)) +
  xlab("Distance (ft) from John Harvard Statue") +
  ylab("Median Interhouse Swipes per Meal")

animate(p, fps = 5)

anim_save("my_anim.gif")

# now I want to produce a gt() table so that you can look at the data in my knit
# html as well since the animation may move too fast

anim_data %>% 
  select(month_year, house, avg_int, avg_total, distance) %>% 
  ungroup() %>% 
  mutate(avg_int = round(avg_int),
         avg_total = round(avg_total),
         distance = paste(round(distance), "feet from John Harvard Statue"),
         month_year = month_year %>% 
           as_factor() %>% 
           fct_relevel("8/2017", "9/2017", "9/2018", "10/2017", 
                       "10/2018", "11/2017", "11/2018", "12/2017", "12/2018")) %>% 
  group_by(house, distance) %>% 
  gt() %>% 
  cols_label(distance = "Distance from John Harvard", 
             month_year = "Month",
             avg_int = "Interhouse Swipes per Meal",
             avg_total = "Total Swipes per Meal") %>% 
  tab_header(title = "Monthly Average Interhouse and Total Swipes per Meal")


```

