---
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Discussion

### Median versus Mean

At certain times in the year, HUDS only operates select dining halls. For example, the dining halls open on a rolling basis following Winter Recess. As a result, some dining halls have uncharacteristically high swipe counts. These outliers make our data susceptible to skewness, which has an impact on the mean and standard deviation, but less of an effect on median and interquartile range. Because of this, I elected to use median as my measure of choice when considering average counts.

### Including Change in Percent and Overall Count of Interhouse Swipes by Meal

The visualizations entitled "Change in Percentage of Interhouse Swipes by Meal" and "Change in Interhouse Swipes by Meal" look relatively similar, and that is because they plot they stem from the same idea but with slightly different measures. The first page maps how much the *percentage* of interhouse swipes out of total swipes changed between the two academic years. The second page displays the difference in the median interhouse swipe *counts* between the two academic years for each house.

While both graph methodologies illustrate the changes in interhouse traffic for each house, the two separate calculations reveal different nuances about the situations in the individual houses. To illustrate this point, consider Currier at lunchtime for both visualizations. The *percentage* of interhouse swipes in Currier at lunch increased by a relatively larger magnitude more than the *counts* of interhouse swipes in Currier at lunch when comparing the size of the bars to the other houses. This means that the count of interhouse swipes in Currier increased by more than the grand total of swipes in Currier. In this specific case, Currier saw an average of 5 more interhouse swipes at lunchtime in the 2018-2019 academic year but an average decrease of 9 in lunch swipes overall.